apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: phonebill-base

resources:
  # Namespace
  - namespace.yaml
  
  # Common resources
  - common/cm-common.yaml
  - common/secret-common.yaml
  - common/secret-imagepull.yaml
  - common/ingress.yaml

  # api-gateway
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - api-gateway/cm-api-gateway.yaml

  # user-service
  - user-service/deployment.yaml
  - user-service/service.yaml
  - user-service/cm-user-service.yaml
  - user-service/secret-user-service.yaml
  
  # bill-service
  - bill-service/deployment.yaml
  - bill-service/service.yaml
  - bill-service/cm-bill-service.yaml
  - bill-service/secret-bill-service.yaml
  
  # product-service
  - product-service/deployment.yaml
  - product-service/service.yaml
  - product-service/cm-product-service.yaml
  - product-service/secret-product-service.yaml
  
  # kos-mock
  - kos-mock/deployment.yaml
  - kos-mock/service.yaml
  - kos-mock/cm-kos-mock.yaml

commonLabels:
  system: phonebill

images:
  - name: acrdigitalgarage01.azurecr.io/phonebill/api-gateway
    newTag: latest
  - name: acrdigitalgarage01.azurecr.io/phonebill/user-service
    newTag: latest
  - name: acrdigitalgarage01.azurecr.io/phonebill/bill-service
    newTag: latest
  - name: acrdigitalgarage01.azurecr.io/phonebill/product-service
    newTag: latest
  - name: acrdigitalgarage01.azurecr.io/phonebill/kos-mock
    newTag: latest