apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-product-service
  namespace: phonebill-dev
data:
  SERVER_PORT: "8083"
  DB_KIND: "postgresql"
  DB_PORT: "5432"
  DDL_AUTO: "update"
  KOS_BASE_URL: "http://kos-mock"
  KOS_CLIENT_ID: "product-service-dev"
  KOS_MOCK_ENABLED: "true"
  REDIS_DATABASE: "2"