apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-common
data:
  CORS_ALLOWED_ORIGINS: "https://phonebill-prod.example.com"
  JWT_ACCESS_TOKEN_VALIDITY: "3600000"
  JWT_REFRESH_TOKEN_VALIDITY: "43200000"
  REDIS_PORT: "6379"
  SPRING_PROFILES_ACTIVE: "prod"
  DDL_AUTO: "validate"