apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-common
data:
  CORS_ALLOWED_ORIGINS: "https://phonebill-staging.example.com"
  JWT_ACCESS_TOKEN_VALIDITY: "18000000"
  JWT_REFRESH_TOKEN_VALIDITY: "86400000"
  REDIS_PORT: "6379"
  SPRING_PROFILES_ACTIVE: "staging"
  DDL_AUTO: "validate"