apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: phonebill
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - phonebill.example.com
    secretName: phonebill-tls-cert
  rules:
  - host: phonebill.example.com
    http:
      paths:
      - path: /api/v1/auth
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 80
      - path: /api/v1/users
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 80
      - path: /api/v1/bills
        pathType: Prefix
        backend:
          service:
            name: bill-service
            port:
              number: 80
      - path: /api/v1/products
        pathType: Prefix
        backend:
          service:
            name: product-service
            port:
              number: 80
      - path: /api/v1/kos
        pathType: Prefix
        backend:
          service:
            name: kos-mock
            port:
              number: 80